[[Plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
  call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])
  call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''
hook_add = '''
nnoremap <Leader>dp :<C-u>Denite file_rec<CR>
nnoremap <Leader>dg :<C-u>Denite grep<CR>
nnoremap <Leader>dy :<C-u>Denite neoyank<CR>
nnoremap <Leader>dr :<C-u>Denite file_rec<CR>
nnoremap <Leader>dm :<C-u>Denite file_mru<CR>
'''

[[plugins]]
repo = 'vim-scripts/camelcasemotion'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#branch#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme = 'molokai'
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_sign_column_always = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_open_list = 1
call ale#balloon#Disable()
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
nnoremap <Leader>gs :<C-u>Gina status<CR>
nnoremap <Leader>gc :<C-u>Gina commit<CR>
nnoremap <Leader>gb :<C-u>Gina branch<CR>
nnoremap <Leader>gB :<C-u>Gina blame<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'posva/vim-vue'
